# -*- coding: utf-8 -*-
"""md5_Hash

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azVpjJ_-9v_azhsSfVdJ6St7FUBPmKvm
"""

import hashlib

text="Life is what happens when you're busy making other plans.— John Lennon."

hash_obj=hashlib.md5(text.encode())

md5_hash=hash_obj.hexdigest()

print(md5_hash)